--Show all the containers that needs to be loaded today
SELECT
    MANIFEST_CONTAINER.MANIFESTID,
    CARGO_CONTAINER.CONTAINERCODE,
    MANIFEST_CONTAINER.CARGOTYPE,
    MANIFEST_CONTAINER.WEIGHT,
    DOCK_MANIFEST.ARRIVALTIME AS "DATE"
FROM 
    ((MANIFEST_CONTAINER
INNER JOIN 
    CARGO_CONTAINER ON MANIFEST_CONTAINER.CONTAINERID = CARGO_CONTAINER.CONTAINERID)
RIGHT OUTER JOIN
    DOCK_MANIFEST ON MANIFEST_CONTAINER.MANIFESTID = DOCK_MANIFEST.MANIFESTID)
WHERE
    TRUNC(DOCK_MANIFEST.ARRIVALTIME) = TRUNC(CURRENT_DATE); 

--Show all the ship dockings today
SELECT 
    DOCK_MANIFEST.MANIFESTID AS "MANIFEST ID",
    SHIP_MANIFEST.SHIPID AS "SHIP ID",
    SHIP.SHIPNAME AS SHIP,
    DOCKING_STATION.DOCKNO AS "DOCK",
    DOCK_MANIFEST.ARRIVALTIME AS "DATE"
FROM 
    (((DOCK_MANIFEST
LEFT OUTER JOIN 
    DOCKING_STATION ON DOCK_MANIFEST.DOCKINGID = DOCKING_STATION.DOCKINGID)
INNER JOIN 
    SHIP_MANIFEST ON SHIP_MANIFEST.MANIFESTID = DOCK_MANIFEST.MANIFESTID)
INNER JOIN 
    SHIP ON SHIP_MANIFEST.SHIPID = SHIP.SHIPID)
WHERE 
    TRUNC(DOCK_MANIFEST.ARRIVALTIME) = TRUNC(CURRENT_DATE)
ORDER BY
    DOCK_MANIFEST.MANIFESTID;
    
--REPLACE:  TRUNC(CURRENT_DATE)
--WITH:     TO_DATE('2020/05/13','YYYY/MM/DD')
--TO:       Test query with any date other than todays date

--ALL SHIPS ARRIVING WITHIN A CERTAIN TIME
SELECT * FROM
(SHIP_MANIFEST INNER JOIN ship ON ship.shipid = ship_manifest.shipid)
    INNER JOIN dock_manifest ON ship_manifest.MANIFESTID = dock_manifest.MANIFESTID
WHERE dock_manifest.arrivaltime BETWEEN TO_DATE('2020-JAN-01', 'YYYY-MON-DD') AND TO_DATE('2020-JAN-05', 'YYYY-MON-DD');

--COUNT OF SHIPS ARRIVING WITHIN A CERTAIN TIME BY COMPANY /// maybe add leaving times too?
SELECT SHIP.SHIPCOMPANY, COUNT(*) FROM
(SHIP_MANIFEST INNER JOIN ship ON ship.shipid = ship_manifest.shipid)
    INNER JOIN dock_manifest ON ship_manifest.MANIFESTID = dock_manifest.MANIFESTID
WHERE dock_manifest.arrivaltime BETWEEN TO_DATE('2020-JAN-01', 'YYYY-MON-DD') AND TO_DATE('2020-JAN-05', 'YYYY-MON-DD')
GROUP BY ship.shipcompany;

--TOTAL WEIGHT OF CARGO BEING CARRIED BY A SHIP AND NUMBER OF CONTAINER
SELECT ship_manifest.manifestid, ship.shipid, ship.shipname, sum(weight) "Total Weight", count(manifest_container.containerid) "Number of Containers", ship.shipcompany FROM
(manifest_container INNER JOIN ship_manifest ON ship_manifest.manifestid = manifest_container.manifestid)
    INNER JOIN ship ON ship_manifest.shipid = ship.shipid   
    GROUP BY ship_manifest.manifestid, ship.shipname, ship.shipid, ship.shipcompany;
    