CREATE TABLE SHIP(
    SHIP_ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1)  UNIQUE PRIMARY KEY,
    SHIP_NAME VARCHAR(50) NOT NULL,
    SHIP_COMPANY VARCHAR(50) NOT NULL
);

CREATE TABLE DOCKING_STATION(
     DOCKING_ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1)  UNIQUE PRIMARY KEY,
     DOCK_NUMBER NUMBER(4)NOT NULL
);

CREATE TABLE CARGO_CONTAINER(
     CONTAINER_ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1)  UNIQUE PRIMARY KEY,
     CONTAINER_NUMBER NUMBER(16)NOT NULL
);

CREATE TABLE SPACEPORT_LOCATION(
     SPACEPORT_ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1)  UNIQUE PRIMARY KEY,
     SPACEPORT_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE SHIP_MANIFEST(
    MANIFEST_ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1)  UNIQUE PRIMARY KEY,
    FOREIGN KEY(SHIP_ID) REFERENCES SHIP(SHIP_ID) NOT NULL,
    FOREIGN KEY(ORIGIN_SPACEPORT_ID) REFERENCES SPACEPORT_LOCATION(SPACEPORT_ID) NOT NULL,
    FOREIGN KEY(DESTINATION_SPACEPORT_ID) REFERENCES SPACEPORT_LOCATION(SPACEPORT_ID) NOT NULL
);

CREATE TABLE DOCK_MANIFEST(
    FOREIGN KEY(MANIFEST_ID) REFERENCES SHIP_MANIFEST(MANIFEST_ID) NOT NULL,
    FOREIGN KEY(DOCKING_ID) REFERENCES DOCKING_STATION(DOCKING_ID) NOT NULL,
    ARRIVAL_TIME DATE NOT NULL,
    DEPARTURE_TIME DATE NOT NULL
);

CREATE TABLE CONTAINER_MANIFEST(
    FOREIGN KEY(MANIFEST_ID) REFERENCES SHIP_MANIFEST(MANIFEST_ID) NOT NULL,
    FOREIGN KEY(CONTAINER_ID) REFERENCES CARGO_CONTAINER(CONTAINER_ID) NOT NULL,
    CARGO_TYPE VARCHAR(100) NOT NULL,
    WEIGHT NUMBER(16,3) NOT NULL
);



